<div class="span6">
<? $this->headTitle('Password Reset'); ?>
<? if($this->status == '200'): ?>
    
    <h3>A reset link has been sent to your inbox.</h3>
    <p>Please go to the email and click on the link. </p>
    
    <small> <?= implode(".", $this->sent) ?> </small>

    
<? elseif($this->status == '404'): ?>
    <h3>This Username was not found</h3>

<? else:?>
 <h3>Please enter your username</h3>
<?= $this->form ?>
<? endif; ?>

</div>
