
<h3>Admin Page Content</h3>
    
    <div class="crud-create-update crud-load-template hidden"
     id="module-bind-crud"
     data-id=''
     data-path='.:crud-module'
     data-form='pagemodulesform'
     data-title="Edit HTML Module Content"
     data-params=''
     data-action='create'
     data-target='js-modules-index'
     data-template='js-crud-edit-modules'></div>
    <?= $this->TableHead( array('Title','Position', '',''), "table table-striped data-table", "js-modules-index" ) ?>
    <? $editPath = "/admin/modules/inline-edit"; ?>
    <?foreach( $this->modules as $m ):?>
    <? $id = $m->id;?>
    <?= $this->TableRow( array( $this->InlineEdit($m->name, $id, $editPath, "name", "Edit Title"),
                                $m->type,
                                "<center>
                                    <a class='crud-create-update icon icon-edit'
                                      data-action='update'
                                      title='edit modules content'
                                      data-bind='module-bind-crud'
                                      data-params='id={$id}'></a>
                                   </center>",
                                   "<center>
                                        <a class='crud-delete icon icon-remove'
                                        data-bind='module-bind-crud'
                                        title='delete module'
                                        data-action='delete'
                                        data-params='id={$id}'></a>
                                   </center>"),
                        "class='crud-row-{$id}'"); ?>
    <?endforeach;?>

<?= $this->TableFoot($this->Crud('create', 'Create New Module', 'module-bind-crud', '', 4)) ?>


<script type="text/plain" id="js-crud-edit-modules">
    <% if( action == '_create' ){%>
    <tr class="crud-row-<%= helpers.escapeHtml(id) %> highlight-child">
    <%}%>
    <td><%= helpers.inlineEdit(helpers.escapeHtml(values.name), id, "<?=$editPath?>", "name", "Edit Title" ) %></td>
    <td><%= helpers.escapeHtml(values.type)%></td>

  <td>
        <center>
            <a class='crud-create-update icon icon-edit'
               data-action='update'
               data-bind='module-bind-crud'
               data-params='id=<%= helpers.escapeHtml(id) %>'></a>
            </center>
    </td>
    
    <td>
        <center>
            <a class='crud-delete icon icon-remove'
               data-bind='module-bind-crud'
               data-action='delete'
               data-params='id=<%= helpers.escapeHtml(id) %>'> </a>
        </center>
    </td>
    
    <% if( action == '_create' ){ %>
        </tr>
    <% } %>
</script>

