<?
$this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyBYt3WjO2eW9zzCrfpxhdl6Q8HJj7ueh_8&sensor=false');
$this->headScript()->appendFile('/js/views/index/events/cal.js');
?>

<div class="span9">
    <h1>Events Calendar</h1>
    <p></p>
    <h2>Center Color Codes</h2>
<table border="0" cellpadding="5">
<tr>
<td><i class="icon-map-marker" style="color:#c4156f;"></i> Fairfax <strong><i>SkillSource</i></strong> Center - Annandale</td>
<td><i class="icon-map-marker" style="color:#742497;"></i> Prince William <strong><i>SkillSource</i></strong> Center</td>
<td><i class="icon-map-marker" style="color:#00af83;"></i> Fairfax <strong><i>SkillSource</i></strong> Center - Alexandria</td>
</tr><tr>
<td><i class="icon-map-marker" style="color:#a21e00;"></i> Loudoun Workforce Resource Center</td>
<td><i class="icon-map-marker" style="color:#e76e37;"></i> Fairfax <strong><i>SkillSource</i></strong> Center - Reston</td>
<td></td>
</tr>
</table>
   <p></p>
   
    <div id="js-calendar-wrapper">
    <?= $this->partial('/index/include/calendar.phtml',
                       array('day'=>date("d"),'year'=>date("Y"),'month'=> date('m'),'customClass'=>'js-events-day',)); ?>
    </div>
   
    <div id="js-events-wrapper" class="">
        <?= $this->partial( '/index/include/events.phtml',array('events'=>$this->events, 'month'=>date("F"), "centerColors"=>$this->centerColors)); ?>
    </div>
</div>