
<?/** 
   *  use the page var to update the color of the
   *  header $this->page
   **/?>

<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->


<div class="container hidden-print">
    <div id="logo"><a href="/"><img src="/img/logo.jpg"></a></div>
          
    <div id="search">
        <div class="right">
            <table width="400">
                <tr>
                    <td valign="top" align="right" width="220">
                        <p><?=$this->GetAuthLink("Board Member / Staff Login");?></p>
                    </td>
                    <td valign="top" align="right">
                        <div id="google_translate_element" style="min-width: 170px;"></div>
                    </td>
                </tr>
            </table>
                
            <table width="400">
                <tr>
                    <td valign="top" align="right">
                        <form name="google-search" method="get" action="http://www.google.com/search">
                            <input type="hidden" name="sitesearch" value="http://www.myskillsource.org/" />
                            <input name="q" type="text" size="15" />
                            <input type="submit" class="submit" value=""  style="min-width: 30px;"/>
                        </form>
                    </td>
                    <td valign="top">
                        <a href="https://www.facebook.com/skillsourcegroup"><img src="/img/facebook.jpg" style="margin-right:2px;margin-left:10px;"></a><a href="https://twitter.com/myskillsource"><img src="/img/twitter.jpg" style="margin-right:2px;"></a><a href="http://www.linkedin.com/company/the-skillsource-group-inc-"><img src="/img/linkedin.jpg" style="margin-right:2px;"></a><a href="http://www.youtube.com/channel/UCsesOsb82W37n8hLf6TGl4Q"><img src="/img/youtube.jpg"></a>
                    </td>
                </tr>
            </table>
            
        </div>
    </div>
    
    
    <div id="nav">
        <ul class="nav">
            <li><a href="/">Home</a></li>
            <li><a href="/page/id/11/who-we-are">Who We Are</a>
                <ul class="subnav">
                   <li><a href="/page/id/1/committees">COMMITTEES</a></li>
                    <li><a href="/page/id/2/board">BOARD MEMBER INFO</a></li>
                    <li><a href="/page/id/3/meetings">Meeting Schedules &amp; Materials</a></li>
                    <li><a href="/page/id/5/wia">WIA - WORKFORCE INVESTMENT ACT</a></li>
                    <li><a href="/page/id/6/programdata">PROGRAM DATA</a></li>
                    <li><a href="/page/id/14/press-room">PRESS ROOM</a></li>
                    <li><a href="/page/id/7/staff">STAFF</a></li>
                    <li><a href="/page/id/16/training.html">TRAINING</a></li>
                    <li><a href="/page/id/9/becomecorpleader">BECOME A CORPORATE LEADER</a></li>
                    <li><a href="/page/id/10/corpleaders">2014 CORPORATE LEADERS</a></li>
                </ul>
            </li>
         
            <li><a href="/page/id/13/locations">Locations</a></li>
            <li><a href="/events">Events</a></li>
            <li><a href="#">Resources</a>
            <ul class="subnav">
            <li><a href="/page/id/36/employer-resources">For Employer</a></li>
            <li><a href="/page/id/30/jobseeker-resources">For Job Seekers</a></li>
            <li><a href="/page/id/20/training-providers">For Training Providers</a></li>
            
            <li><a href="/page/id/18/finance-audit-information">Finance &amp; Audit Info</a></li>
            <li><a href="/page/id/19/plans-policies">Plans &amp; Policies</a></li>
            <li><a href="/page/id/17/annual-report">Annual Report</a></li>
   
            <li><a href="/page/id/21/center-certifications">Center Certifications</a></li>
            <li><a href="/page/id/22/partner-programs">Partner Programs</a></li>
            <li><a href="/page/id/23/other-wibs">Other WIBs</a></li>
            
            </ul>
            </li>
            <li><a href="/page/id/46/contact" class="last">Contact Us</a></li>
        </ul>
    </div>
    
</div>










