
<?/** 
   *  use the page var to update the color of the
   *  header $this->page
   **/?>


<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/"><?=SITE_NAME?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="/">Home</a></li>
   
                            <li class="dropdown">
                                    <li><a href="/providers">Providers</a></li>
                                    <li class="divider"></li>
                                
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Placeholder<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Link 1</a></li>
                                    <li><a href="#">Link 2</a></li>
                                   <li class="divider"></li>
                                   <li class="nav-header">Link Header</li>
                                   <li><a href="#">Link 3</a></li>
                                    
                                </ul>
                            </li>
                        </ul>
                        <div class="navbar-form pull-right">
                            <?= $this->GetAuthLink()?>
                        </div>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>