<div class="row" >
<div class="span8" >
    <?= $this->TableHead( array('Industry'), "table table-striped", "js-groups-index" ) ?>
        <?foreach( $this->parents as $p ):
        
            $map = '';
            foreach($this->children as $c ) {
                if(  $c->parent_id == $p->id ) {
                    $map .= "<li><a class='industry-view' data-id='{$c->id}'>{$c->name}</a></li>";
                    }            
           }
           
           if($map != '') {
              $map = "<!-- a class='pointer pull-right view-subcategories' data-parent='{$p->id}'>Subcategories <i class='icon-resize-vertical'> </i></a-->
                      <div class='toggle-industry-sub-cats' id='children-of-{$p->id}' style='display:block;'><uL style='margin:0px 0px 0px 10px; padding:0px;'>" . $map . "</uL></div>"; 
           } 
        
        ?>
            <?= $this->TableRow(array(
                                "<a class='industry-view' data-id='{$p->id}' ><strong>{$p->name}</strong></a> {$map}"
                                
                                ) ); ?>
        <?endforeach;?>
    <?= $this->TableFoot() ?>
</div>
</div>
