<div style="margin-bottom: 2px;">
Starts With <input type="radio" name="js-regex" class="js-regex" id="js-regex-starts" value="starts"  />
Contains <input type="radio" name="js-regex" class="js-regex" id="js-regex-contains" value="contains" checked="checked" /> 
</div>   


<div class="input-append">
<input class="span2" id="js-search-members" data-path="<?=$this->path?>" type="text" style="height: 20px;">
<div class="btn-group">
<button class="btn dropdown-toggle" data-toggle="dropdown" style="height: 30px;">
<span id="js-current-search-field">Search By Provider&#47;Program Name</span>
<span class="caret"></span>
</button>
<ul class="dropdown-menu">
<li><a data-href="name" data-label="Search By Provider&#47;Program Name" class="js-search-by">Search By Provider&#47;Program Name</a></li>
<li><a data-href="tags" data-label="Industries" class="js-search-by">Industries</a></li>
<li><a data-href="city" data-label="City" class="js-search-by">City</a></li>

</ul>
</div>
</div>   

<div id="js-alphabet-search" style="text-align: center;">
  
  
<?
$cities = array();
foreach( $this->locations as $location ){
   $l = strtoupper($this->truncate($location['city'], 1, ""));
   if(!in_array($l, $cities)){
    $cities[] = $l;
   }
}

$names = array();
foreach( $this->providers as $name ){
   $n = strtoupper($this->truncate($name['name'], 1, ""));
   if(!in_array($n, $names)){
    $names[] = $n;
   }
}

$tags = array();
foreach( $this->providers as $p ){
   $t = strtoupper($this->truncate($p['tags'], 1, ""));
   if(!in_array($t, $tags)){
    $tags[] = $t;
   }
}


?>  
<div class="city-letter-search js-letters">                    
<?foreach( range('A', 'ZZ') as $letter ):?>
    
    <a <?if(in_array($letter, $cities)):?>
        data-href="#<?=$letter?>"
      <?endif;?>
      class="<?if(in_array($letter, $cities)):?>js-alpha-sort<?else:?>disabled<?endif;?>"
      style=" display: inline-block; width: 20px;"><?=$letter?></a> 
    
<?endforeach;?>
</div>

<div class="name-letter-search js-letters" style="display:none;">                    
<?foreach( range('A', 'ZZ') as $letter ):?>
        <a 
        <?if(in_array($letter, $names)):?>
            data-href="#<?=$letter?>"
            class="js-alpha-sort"
        <?else:?>
            class="disabled"
        <?endif;?>
        style=" display: inline-block; width: 20px;"><?=$letter?></a> 
    
<?endforeach;?>
</div>


<div class="tags-letter-search js-letters" style="display:none;">                    
<?foreach( range('A', 'ZZ') as $letter ):?>
        <a 
        <?if(in_array($letter, $tags)):?>
            data-href="#<?=$letter?>"
            class="js-alpha-sort"
        <?else:?>
            class="disabled"
        <?endif;?>
        style=" display: inline-block; width: 20px;"><?=$letter?></a> 
    
<?endforeach;?>
</div>


<div class="zip-letter-search js-letters" style="display:none;">                    
<?foreach( range('0', '9') as $number ):?>
        <a data-href="#<?=$number?>"
           class="js-alpha-sort"
           style=" display: inline-block; width: 20px;"><?=$number?></a> 
    
<?endforeach;?>
</div>


                    
<hr style="border-bottom: solid 1px #f6f6f6;" />
                    
</div>
                    
<div id="js-search-results">
    
    
</div>