<div id="async-login-info"> </div>
<form id="asyncLogin">
    <label for="username">Username:</label>
    <input type="text" name="username" id="log-in-username" /><br />
    <label for="username">Password:</label>
    <input type="password" name="password" id="log-in-password" /><br />
    <input type="button" value="log-in" id="asyncLogin-submit" class="btn btn-primary" />    
</form>



<a href="/password"> I forgot my password</a>