<? $this->headLink()->appendStylesheet('/css/vendor/bootstrap-datatable.css'); ?>
<? $this->headScript()->appendFile('/js/vendor/jquery.dataTables.min.js');?>
<? $this->headScript()->appendFile('/js/vendor/jquery.dataTable.tools.js');?>


<h2><span id="js-curr-month"><?=$this->month?></span> Events</h2>
<?if(isset($this->events) && is_array($this->events)):?>
 
 <?= $this->TableHead( array('Center', 'Title','Date','Starts','Ends', 'Quick', 'View'), "table table-striped data-table dataTable small-txt data-table", "event-list" ) ?>

 <?foreach($this->events as $k=>$e ):?>
 
 <?
 
  $color = "#000";
 
  if( isset($this->centerColors[(int)$e['center_id']]) ) {
    
    $color = $this->centerColors[(int)$e['center_id']]['hex'];
  }
 
  $cl = ($e["center_id"] != 0) ? "js-center-info pointer" : "" ;
 
 ?>
 
 <?= $this->TableRow( array(" <i class='".$cl." rounded-corners' data-stats='hidden' data-load='false' data-popuppath='/center-info/id/".$e["center_id"]."' style='background-color:$color;'> </i>
                            
                            <span class='hidden'>".$e['center_id']."</span>
                            ",
                             
                            '<span title="'.$this->escape($e['title']).'">'.$this->Truncate($e['title'], 40) .'</span>',
                             date("m/d/Y", strtotime($e['created'])),
                             $e['start_time'],
                             $e['end_time'],
                             " <a class='js-view-event rounded-corners' data-id='".$e["id"]."'> <i class='icon-calendar'> </i> </a> ",
                             " <a href='/event-detail/id/".$e["id"]."/event/".Base_Functions_Strings::Slug($e['title'])."'> <i class='icon-share'> </i> </a> ",
                             
                             ), 
                     "class='event-row-".$e["id"]."'"); ?>
 <?endforeach;?>

 <?= $this->TableFoot() ?>
 
 <?endif?>
 
 <script type="text/javascript">
   $(document).ready(function(){
    
     $('.data-table').dataTable( {
		"sDom": "<'row'<'span2'l><'span7'f>r>t<'row'<'span6'i><'span6'p>>",
		"sPaginationType": "bootstrap",
		"oLanguage": {
			"sLengthMenu": "_MENU_ records per page"
		}
                } );
    
    
  var __evetns = <?=json_encode($this->events);?>;
 
  if (Events.Colors == null) {
        Events.Colors = <?=json_encode($this->centerColors);?>;
  }
 
  
  for(var key in __evetns) {
                 var info = __evetns[key];  
                 var date = info.created;
                 var count = 1;
                 
                 var color = {hex:"#000"};
                 
                 try{
                 if (typeof Events.Colors == 'object') {
                   
                    if ( Events.Colors[info.center_id] !== undefined) {
                        color = Events.Colors[info.center_id];
                    }  
                   
                 }
                 }catch(e){
                    console.log(e);
                    
                 }
                 
                 
                 var div =  $("#cal-"+date);
                 if (div.length > 0) {
                     div.append(" <i class='js-view-event icon-map-marker pointer' style='color:"+color.hex+"' title='"+info.title+"'  data-id='"+info.id+"'></i> ");

               }
    }

  });
 
    
 </script>
 
 

 