<? $this->headTitle('Training Providers');?>
<? $this->headLink()->appendStylesheet('/css/vendor/bootstrap-datatable.css'); ?>
  
<? $this->headScript()->appendFile('/js/views/providers/index.js');?>
<? $this->headScript()->appendFile('/js/vendor/jquery.dataTables.min.js');?>
<? $this->headScript()->appendFile('/js/vendor/jquery.dataTable.tools.js');?>
<? $this->headScript()->appendFile('/js/vendor/sweet-pages.js');?>

    <div class="span9">
    <h3>Training Providers Directory</h3>
        <div class="tabbable">
            
            <ul class="nav nav-tabs">
                <li class=""><a href='#tab0' data-toggle="tab">Industries</a></li>
                <!--li class=""><a href="#tab01" data-toggle="tab">Programs</a></li-->
                <li class="active">
                    <a href="#tab1" class="tabContainer1" data-toggle="tab">A - H</a>
                </li>
                <li>
                    <a href="#tab2" class="tabContainer2" data-toggle="tab">I - P</a>
                </li>
                <li>
                    <a href="#tab3" class="tabContainer3" data-toggle="tab">Q - Z</a>
                </li>
                <li>
                    <a href="#tab4" data-toggle="tab">Search</a></li>
            </ul>
            
            <div class="tab-content">
                
                <div class="tab-pane" id="tab0">
                    <?= $this->partial('/provider/partials/industries.phtml', 'default',
                                      array( 'parents' => $this->baseIndustries,
                                             'children' => $this->nestedIndustries
                                            ));?>    
                </div>
                
                <!--div class="tab-pane" id="tab01">
                    <?
                    /*
                    echo $this->partial('/provider/partials/program-types.phtml', 'default',
                                  array( 'programs' => $this->programsGroups));
                    */              
                                  ?> 
                </div-->
                
                <div class="tab-pane active pos-rel" id="tab1">
                    <?= $this->partial('/provider/partials/display.phtml', 'default',
                                       array('providers'=>$this->providersA_H,
                                             'locations'=>$this->locations,
                                             'page'=>'page1'));?>               
                </div>
        
                <div class="tab-pane pos-rel" id="tab2">
                    <?= $this->partial('/provider/partials/display.phtml', 'default',
                                       array('providers'=>$this->providersI_P,
                                             'locations'=>$this->locations,
                                             'page'=>'page2'
                                             ));?>     
                    </div>
        
                <div class="tab-pane pos-rel" id="tab3">
                    <?= $this->partial('/provider/partials/display.phtml', 'default',
                                       array('providers'=>$this->providersQ_Z,
                                             'locations'=>$this->locations,
                                             'page'=>'page3'));?>     
                    
                </div>
                
                
                <div class="tab-pane" id="tab4" style="min-height:350px;">
                      <?= $this->FavsList();?>
                    
                       <?= $this->partial('/provider/partials/search.phtml', 'default',
                                          array('path'=>'/providers/search/',
                                                'locations'=>$this->locationsFilter,
                                                'providers'=>$this->providersFilter)); ?>
                </div>
                
            </div>
            
        </div>
        
    </div>


