<? if( $this->disableLayout == false ): ?>
    <? $this->headTitle('Training Providers');?>
    <? $this->headScript()->appendFile('/js/views/providers/index.js');?>
    <h3>Training Providers Directory</h3>
    <hr>
    <?= $this->partial('/provider/partials/search.phtml', 'default', array()); ?> 
<?endif;?>
<?
$count1 = count($this->providers);
$plural1 = ($count == 1) ? '' : 's';

$count2 = count($this->programs);
$plural2 = ($count == 1) ? '' : 's';

?>

<h2>Found <?=$count1?> provider<?=$plural1?> and <?=$count2?> program<?=$plural2?></h2>

<?= $this->partial('/provider/partials/display.phtml', 'default',
                   array('providers'=>$this->providers,
                         'programs'=>$this->programs,
                         'locations'=>$this->locations));?>